/* ============================================================
   i18n.js — 中英双语切换模块
   Usage: data-i18n="key" 标记需要翻译的元素
   ============================================================ */

const I18N_DICT = {
  // ---- Navigation ----
  'nav.home':       { en: 'Home',       zh: '首页' },
  'nav.methodology':{ en: 'Methodology', zh: '方法论' },
  'nav.lang_switch':{ en: '中文',        zh: 'English' },

  // ---- Home: Hero ----
  'hero.title':     { en: 'Conditional Autoencoder Factor Models: Evidence from China\'s A-Share Market',
                      zh: '条件自编码器因子模型：来自中国A股市场的证据' },
  'hero.author':    { en: 'Huang Zhongtian · M.Sc. Finance · Jinan University',
                      zh: '黄中天 · 金融硕士 · 暨南大学' },
  'hero.stat1_val': { en: '+312.1%',     zh: '+312.1%' },
  'hero.stat1_lbl': { en: 'CA(1-layer) 5yr Total Return vs CSI 300 +24.2%',
                      zh: 'CA(1-layer) 5年累计收益 vs 沪深300仅+24.2%' },
  'hero.stat2_val': { en: 'Sharpe 1.30', zh: 'Sharpe 1.30' },
  'hero.stat2_lbl': { en: 'Highest Annualized Sharpe Ratio',
                      zh: '最高年化夏普比率' },
  'hero.stat3_val': { en: '87 Features', zh: '87个特征' },
  'hero.stat3_lbl': { en: 'Across 10 Categories of A-Share Characteristics',
                      zh: '覆盖10大类A股特征因子' },
  'hero.download_pdf': { en: 'Download PDF', zh: '下载论文PDF' },
  'hero.github_repo':  { en: 'GitHub Repo',  zh: 'GitHub代码仓库' },

  // ---- Home: Abstract ----
  'abstract.title': { en: 'Abstract',    zh: '摘要' },
  'abstract.text':  { en: 'We systematically evaluate Conditional Autoencoder (CA) asset pricing models in China\'s A-share market from 2020 to 2024. Using 87 firm characteristics across 10 categories, we compare traditional factor models (FF), PCA, IPCA, and CA models with varying network depths (0–3 hidden layers). CA(1-layer) delivers the strongest investment performance: a 5-year cumulative return of +312.1% (vs. CSI 300\'s +24.2%) after A-share transaction costs, with an annualized Sharpe ratio of 1.30. IPCA-extracted factors align closely with classical value, size, momentum, and liquidity dimensions. Our findings demonstrate that nonlinear conditional factor models offer both superior predictive power and practical investment value in China\'s retail-dominated, policy-intensive market environment.',
                      zh: '本文系统检验了条件自编码器（CA）资产定价模型在中国A股市场2020–2024年的适用性。基于87个公司特征因子和10大分类体系，我们比较了传统因子模型（FF）、PCA、IPCA和不同网络深度（0–3个隐藏层）的CA模型。CA(1-layer)展现出最优的投资绩效：扣除A股交易成本后5年累计收益+312.1%（沪深300仅+24.2%），年化夏普比率1.30。IPCA提取的因子结构与经典价值、规模、动量、流动性维度高度吻合。研究表明，在中国散户主导、政策干预频繁的市场环境中，非线性条件因子模型兼具预测优势与实际投资价值。' },

  // ---- Home: Key Result ----
  'key_result.title': { en: 'Key Result: Cumulative Return Comparison',
                        zh: '核心结果：累计收益对比' },
  'key_result.caption': { en: 'CA models outperform CSI 300 by 10×+ at K≥2, after all A-share transaction costs.',
                          zh: 'CA模型在K≥2时跑赢沪深300十倍以上，已扣除全部A股交易成本。' },

  // ---- Home: Performance ----
  'perf.title':     { en: 'Performance Summary',         zh: '表现汇总' },
  'perf.panel_a':   { en: 'Panel A: Total Return (%)',  zh: '表A：累计收益（%）' },
  'perf.panel_b':   { en: 'Panel B: Annualized Sharpe Ratio', zh: '表B：年化夏普比率' },
  'perf.panel_c':   { en: 'Panel C: Maximum Drawdown (%)',   zh: '表C：最大回撤（%）' },
  'perf.note':      { en: 'Top-decile long-only, monthly rebalancing, value-weighted (VW), after A-share transaction costs (stamp duty 5bp sell-side, commission 2.5bp, transfer fee 0.2bp). FF limited to K ≤ 4. Bold = best in column. Green = positive, Red = negative.',
                      zh: 'Top-Decile仅做多组合，月度调仓，市值加权，扣除A股交易成本（印花税5bp卖方、佣金2.5bp、过户费0.2bp）。FF限于K≤4。加粗=列内最优。绿色=正收益，红色=负收益。' },

  // ---- Home: Results by K ----
  'results.title':  { en: 'Backtest Charts — Value-Weighted (VW)', zh: '回测图表 — 市值加权（VW）' },
  'results.best':   { en: 'Best', zh: '最优' },

  // ---- Home: Footer ----
  'footer.last_updated': { en: 'Last updated', zh: '最后更新' },
  'footer.generated':    { en: 'Generated by CAbackend — A-Share Factor Model Backtest Engine',
                           zh: '由CAbackend生成 — A股因子模型回测引擎' },

  // ---- Methodology ----
  'method.title':         { en: 'Methodology & Data', zh: '方法论与数据' },
  'method.data_overview': { en: 'Data Overview', zh: '数据概览' },
  'method.data_source':   { en: 'Data Sources: CSMAR & RESSET · Jan 2011 – Dec 2024 · 5,447 A-share stocks (ex-ST) · Risk-free rate: 1yr government bond yield · Market return: float-cap-weighted all-stock return',
                            zh: '数据来源：CSMAR & RESSET · 2011.01–2024.12 · 5447只A股（剔除ST） · 无风险利率：一年期国债收益率 · 市场收益：流通市值加权全市场收益' },
  'method.pipeline':      { en: 'Data Processing Pipeline', zh: '数据处理流水线' },
  'method.factor_class':  { en: 'Factor Classification System', zh: '因子分类体系' },
  'method.desc_stats':    { en: 'Descriptive Statistics', zh: '描述性统计' },
  'method.model_arch':    { en: 'Model Architecture', zh: '模型架构' },
  'method.backtest':      { en: 'Backtest Methodology', zh: '回测方法' },
  'method.filter.placeholder': { en: 'Search features...', zh: '搜索特征...' },
  'method.filter.all':    { en: 'All Categories', zh: '全部分类' },
  'method.stats.cols':    { en: 'Feature | Label | Mean | Std | Min | P5 | P95 | Max | Missing%',
                            zh: '特征 | 标签 | 均值 | 标准差 | 最小值 | P5 | P95 | 最大值 | 缺失率%' },

  // Process flow steps
  'process.step1_title': { en: 'Winsorize', zh: '缩尾处理' },
  'process.step1_desc': { en: '(5%, 95%) by month', zh: '按月(5%, 95%)缩尾' },
  'process.step2_title': { en: 'Normalize', zh: '标准化' },
  'process.step2_desc': { en: 'Min-Max to [-1, 1]', zh: 'Min-Max至[-1,1]' },
  'process.step3_title': { en: 'Fill Missing', zh: '缺失值填充' },
  'process.step3_desc': { en: '3-stage hierarchical', zh: '三阶段分层填充' },
  'process.step4_title': { en: 'Portfolio Construction', zh: '组合构建' },
  'process.step4_desc': { en: 'Managed portfolio returns', zh: '特征管理组合收益' },

  // Model descriptions
  'model.ff':   { en: 'Fama-French (CH4) — Idiosyncratic volatility factors, K=1–4', zh: 'Fama-French (CH4) — 特质波动率因子，K=1–4' },
  'model.pca':  { en: 'PCA — Asymptotic Principal Component Analysis, K=1–6', zh: 'PCA — 渐近主成分分析，K=1–6' },
  'model.ipca': { en: 'IPCA — Instrumented PCA, linear feature-to-factor mapping, K=1–6', zh: 'IPCA — 工具化主成分分析，线性特征-因子映射，K=1–6' },
  'model.ca':   { en: 'CA (0–3 layers) — Conditional Autoencoder, nonlinear encoder-decoder, K=1–6', zh: 'CA (0–3层) — 条件自编码器，非线性编码器-解码器，K=1–6' },

  // Backtest method
  'backtest.formula_caption': { en: 'Expected return for stock i at month t:',
                                zh: '股票i在月份t的预期收益：' },
  'backtest.desc': { en: 'At each month-end, stocks are sorted into deciles by expected return. The top decile (D10) is held for one month as a long-only portfolio. Monthly rebalancing with a rolling expanding window for λ estimation.',
                     zh: '每月末，按预期收益将股票分为十等分组，买入最高组（D10）持有一个月。月度调仓，使用滚动扩展窗口估计λ。' },
  'backtest.costs': { en: 'A-Share Transaction Costs (per round-trip ≈ 10.4 bp):',
                      zh: 'A股交易成本（每轮换仓≈10.4 bp）：' },
  'backtest.benchmark': { en: 'Benchmark: CSI 300 Index (沪深300)', zh: '基准：沪深300指数' },

  // Misc
  'section.toggle': { en: 'Show more', zh: '展开更多' },
  'section.toggle_less': { en: 'Show less', zh: '收起' },
};

let currentLang = localStorage.getItem('site-lang') || 'en';

function i18n(key) {
  const entry = I18N_DICT[key];
  if (!entry) return key;
  return entry[currentLang] || entry['en'] || key;
}

function switchLang() {
  currentLang = currentLang === 'en' ? 'zh' : 'en';
  localStorage.setItem('site-lang', currentLang);
  applyI18n();
}

function applyI18n() {
  // Update all elements with data-i18n attribute
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    const text = i18n(key);
    if (text) el.textContent = text;
  });

  // Update placeholder attributes
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    el.placeholder = i18n(key);
  });

  // Update lang switch button text
  const btn = document.getElementById('lang-switch-btn');
  if (btn) btn.textContent = i18n('nav.lang_switch');

  document.documentElement.lang = currentLang;

  // Re-render any dynamic content
  if (typeof renderPerformanceTables === 'function') renderPerformanceTables();
  if (typeof renderFactorTable === 'function') renderFactorTable();
}

document.addEventListener('DOMContentLoaded', () => {
  document.getElementById('lang-switch-btn')?.addEventListener('click', switchLang);
  applyI18n();
});
